---
# copyright Utrecht University
# This playbook deploys Dokuwiki on a CentOS 7 server

- hosts: localhost
  gather_facts: False
  pre_tasks:
    - name: Verify Ansible version meets requirements
      assert:
        that: "ansible_version.full is version('2.7', '>=')"
        msg: >
          "You must update Ansible to at least 2.7 to deploy EPOS-MSL CKAN."


- name: Provision Dokuwiki
  hosts: all
  become: yes
  roles:
    - common
    - certificates
    - apache
    - php
    - dokuwiki
